local ESP={Enabled=false,NameESPEnabled=false,Objects={},Settings={Text="Display",IncludeLocalPlayer=false,Color=Color3.fromRGB(255,255,255),TeamCheck=false}}local Players=game:GetService("Players")local LocalPlayer=Players.LocalPlayer;function ESP:AddNameESP(opts)opts=setmetatable(opts or{},{__index=self.Settings})for _,player in ipairs(Players:GetPlayers())do if not opts.IncludeLocalPlayer and player==LocalPlayer then continue end self:_addBillboard(player,opts)end Players.PlayerAdded:Connect(function(player)if opts.IncludeLocalPlayer or player~=LocalPlayer then self:_addBillboard(player,opts)end end)end;function ESP:_addBillboard(player,opts)local function createESP(char)if not char then return end local head=char:FindFirstChild("Head")if not head then return end local bill=Instance.new("BillboardGui")bill.Adornee=head;bill.Size=UDim2.new(0,200,0,30)bill.StudsOffset=Vector3.new(0,2,0)bill.AlwaysOnTop=true local label=Instance.new("TextLabel",bill)label.Size=UDim2.new(1,0,1,0)label.BackgroundTransparency=1 label.TextStrokeTransparency=0.5 label.Font=Enum.Font.SourceSansBold label.TextScaled=true bill.Parent=game.CoreGui self.Objects[player]={Billboard=bill,Label=label,Options=opts}task.spawn(function()while bill.Parent and self.Objects[player]do local data=self.Objects[player]local o=data.Options if ESP.Enabled and ESP.NameESPEnabled then label.TextColor3=o.Color label.Text=(o.Text=="User"and player.Name)or player.DisplayName if o.TeamCheck and player.Team==LocalPlayer.Team then bill.Enabled=false else bill.Enabled=true end else bill.Enabled=false end task.wait(1)end end)end;if player.Character then createESP(player.Character)end player.CharacterAdded:Connect(createESP)end;function ESP:RemoveNameESP(player)if player then local obj=self.Objects[player]if obj then obj.Billboard:Destroy()self.Objects[player]=nil end else for p,obj in pairs(self.Objects)do if obj.Billboard then obj.Billboard:Destroy()end end self.Objects={}end end;return ESP
print[[
thanks for using! <3
  _    _   _ __  __ ___ _   _    _
 | |  | | | |  \/  |_ _| \ | |  / \
 | |  | | | | |\/| || ||  \| | / _ \
 | |__| |_| | |  | || || |\  |/ ___ \
 |_____\___/|_|  |_|___|_| \_/_/   \_\
LumiESP - A simple ESP Library
]]